#!/bin/sh
# PROVIDE: flexget
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="flexget"
rcvar="flexget_enable"
load_rc_config $name

: ${flexget_enable:="NO"}
: ${flexget_app_dir:="/usr/local/flexget"}
: ${flexget_user:="flexget"}

required_dirs="$flexget_app_dir"
procname="$flexget_app_dir/bin/python3.9"

# For 'argument_cmd', '${name}_chdir' doesn't work for unknown reason.
# It's a bit clunky, but I'm moving with 'argument_precmd'.
start_precmd="cd $flexget_app_dir"
stop_precmd="cd $flexget_app_dir"
status_precmd="cd $flexget_app_dir"
start_cmd="$flexget_app_dir/bin/flexget daemon start -d"
stop_cmd="$flexget_app_dir/bin/flexget daemon stop"
status_cmd="$flexget_app_dir/bin/flexget daemon status"

run_rc_command "$1" 
