#!/bin/sh
# PROVIDE: flexget
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name=flexget
rcvar=flexget_enable
load_rc_config $name

: ${flexget_enable:="NO"}
: ${flexget_app_dir:="/home/flexget/flexget"}
: ${flexget_user:="flexget"}

procname="${flexget_app_dir}/bin/python3.9"
start_cmd="${name}_start"
stop_cmd="${name}_stop"
status_cmd="${name}_status"

flexget_start()
{
        /usr/local/bin/sudo -H -u ${flexget_user} ${flexget_app_dir}/bin/flexget daemon start -d
}

flexget_stop()
{
        /usr/local/bin/sudo -H -u ${flexget_user} ${flexget_app_dir}/bin/flexget daemon stop
}

flexget_status()
{
        /usr/local/bin/sudo -H -u ${flexget_user} ${flexget_app_dir}/bin/flexget daemon status
}

run_rc_command "$1" 
